---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dataset-config
  namespace: caiogrossi
data:
  # Dataset URL - pointer to the actual dataset
  # Update this to change which dataset is used for training
  dataset.url: "https://homepages.dcc.ufmg.br/~cunha/hosted/cloudcomp-2023s2-datasets/2023_spotify_ds1.csv"
  
  # Dataset version - semantic versioning
  # Change this to trigger new model training
  dataset.version: "1.0.0"
  
  # Dataset name for reference
  dataset.name: "music-playlists"
  
  # Training parameters (optional - can also be in training service)
  min_support: "0.05"
  min_confidence: "0.3"
