---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-api
  namespace: caiogrossi
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: caiogrossi-frontend-api
  template:
    metadata:
      labels:
        app: caiogrossi-frontend-api
    spec:
      containers:
      - name: frontend-api
        image: caiosgrossi/playlist-recommender-system:frontend-api-v1.0.4
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 50005
        volumeMounts:
        - name: model-storage
          mountPath: /app/models
          subPath: dev
          readOnly: true
        livenessProbe:
          httpGet:
            path: /health
            port: 50005
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 50005
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      volumes:
      - name: model-storage
        persistentVolumeClaim:
          claimName: model-pvc