---
apiVersion: batch/v1
kind: Job
metadata:
  name: training-job-v5-0-0
  namespace: caiogrossi
  labels:
    app: caiogrossi-recommender-trainer
    version: "5.0.0"
    managed-by: argocd
spec:
  ttlSecondsAfterFinished: 600
  backoffLimit: 2
  template:
    metadata:
      labels:
        app: caiogrossi-recommender-trainer
    spec:
      restartPolicy: OnFailure
      containers:
      - name: training-job
        image: caiosgrossi/playlist-recommender-system:training-job-v5.0.0
        imagePullPolicy: IfNotPresent
        env:
        - name: DATASET_URL
          valueFrom:
            configMapKeyRef:
              name: dataset-config
              key: dataset.url
        - name: DATASET_VERSION
          valueFrom:
            configMapKeyRef:
              name: dataset-config
              key: dataset.version
        - name: DATASET_NAME
          valueFrom:
            configMapKeyRef:
              name: dataset-config
              key: dataset.name
        volumeMounts:
        - name: model-storage
          mountPath: /app/models
          subPath: production
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      volumes:
      - name: model-storage
        persistentVolumeClaim:
          claimName: model-pvc
