---
apiVersion: v1
kind: Service
metadata:
  name: recommendation-service
  namespace: caiogrossi
spec:
  selector:
    app: caiogrossi-recommender
  ports:
    - protocol: TCP
      port: 5006
      targetPort: 50005
      name: http
  type: ClusterIP
